name: CI-CD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build_test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Upgrade pip & install deps
        run: |
          python -m pip install --upgrade pip wheel
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest pytest-cov

      - name: PyTest (with coverage)
        run: |
          mkdir -p test-results
          pytest -q tests --junitxml=test-results/pytest.xml --cov=src --cov-report=xml

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results/pytest.xml

      - name: Create deploy package (zip)
        run: |
          rm -rf _pkg && mkdir _pkg
          cp -R src _pkg/src
          [ -f run.sh ] && cp run.sh _pkg/
          [ -f run.bat ] && cp run.bat _pkg/
          [ -f requirements.txt ] && cp requirements.txt _pkg/
          [ -f pyproject.toml ] && cp pyproject.toml _pkg/
          cd _pkg && zip -r ../app.zip .
          cd ..

      - name: Upload app artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-zip
          path: app.zip

  deploy_dev:
    name: Deploy to Dev (calc-dev-web)
    needs: build_test
    runs-on: ubuntu-latest
    environment: dev-web
    steps:
      - name: Download app artifact
        uses: actions/download-artifact@v4
        with:
          name: app-zip
          path: .

      - name: Azure WebApp Deploy (Dev)
        uses: azure/webapps-deploy@v3
        with:
          app-name: "calc-dev-web"
          publish-profile: ${{ secrets.DEV_PUBPROFILE }}
          package: "app.zip"

  deploy_prod:
    name: Deploy to Prod (calc-prod-web)
    needs: deploy_dev
    runs-on: ubuntu-latest
    environment: prod-web   # gate with required reviewers in Environment settings
    steps:
      - name: Download app artifact
        uses: actions/download-artifact@v4
        with:
          name: app-zip
          path: .
 
      - name: Azure WebApp Deploy (Prod)
        uses: azure/webapps-deploy@v3
        with:
          app-name: "calc-prod-web"
          publish-profile: ${{ secrets.PROD_PUBPROFILE }}
          package: "app.zip"
